### ISSUE TITLE
Bug on Wild Tile after placing wire

### ISSUE THREAD

**Issue by darmo1112** [ekfvoddl3536/OniMods#6] opened 2024-03-17 07:44 UTC
![image](https://github.com/ekfvoddl3536/OniMods/assets/21287514/6191a3c0-82e5-4182-b06b-1ef67cbd1283)
![image](https://github.com/ekfvoddl3536/OniMods/assets/21287514/0123e6bf-d555-430b-9dd9-1ad89fb0e03b)

i found bug at wild tile... it didnt count as wall after i put wire in it..
pip can go through it, after reload the game.. it still same..

then i try destroy the wire, and reload the game... it become normal again...
![image](https://github.com/ekfvoddl3536/OniMods/assets/21287514/b581b7d8-72e5-4a90-9819-14f5af360e83)

**Comment by ekfvoddl3536** [comment] 2024-04-20 02:25
I was unable to reproduce this issue in the latest version.  
  
I experimented with various wires including regular, conductive, and heavy-watt wires (the latter does pass through, which I consider a bug, but I don’t mind it so I have no intention to improve it at this moment), but I couldn’t find any problems.  
  
Is there anything specific I should pay attention to in order to reproduce this issue?

**Comment by ekfvoddl3536** [comment] 2024-08-10 19:32
I will consider the issue resolved and close the issue. If the issue occurs again, please re-open it.

**Closed as completed by ekfvoddl3536** 2024-08-10 19:32 UTC
Labels: bug
